# -------------------------------------------------
# Ask group action
# -------------------------------------------------
- name: Ask Preparing Action
  pause:
    prompt: |
      ===================================
      Select Type of Node:

      1. Install n8n
      2. Test n8n
      3. ......
      4. Exit

      Choose action (1-4):
  register: type_node

- name: Set action fact
  set_fact:
    group_action: "{{ type_node.user_input | trim }}"

# -----------------------------
# Starting Preparing Based On Node
# -----------------------------
- name: Preparing Bastion Node
  ansible.builtin.include_tasks: setup-n8n.yml
  when: type_node.user_input | trim == '1'

- name: Preparing Master Node
  ansible.builtin.include_tasks: test-n8n.yml
  when: type_node.user_input | trim == '2'

- name: Preparing Worker Node
  ansible.builtin.include_tasks: manage-samba-user.yml
  when: type_node.user_input | trim == '3'

- name: Exit
  debug:
    msg: "Goodbye!"
  when: type_node.user_input | trim == '4'

- meta: end_play
  when: type_node.user_input | trim == ''

  vars:
    operation_map:
      '1': 'bastion'
      '2': 'master'
      '3': 'worker'
      '4': 'exit'
