---
- name: Setup Harbor with Docker
  become: yes
  block:


    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_check
      failed_when: false
      changed_when: false

    - name: Installation Docker
      ansible.builtin.include_tasks: docker.yml
      when: docker_check.rc != 0


    - name: Disable systemd-resolved
      systemd:
        name: systemd-resolved
        enabled: no
        state: stopped
    
    
    - name: Remove resolv.conf
      file:
        path: /etc/resolv.conf
        state: absent


    - name: Set temporary DNS
      copy:
        dest: /etc/resolv.conf
        content: "nameserver 8.8.8.8"



    - name: Set hostname
      hostname:
          name: "{{ inventory_hostname }}"



    - name: Add hosts entry
      lineinfile:
        path: /etc/hosts
        line: "{{ ip }} {{ hostname_name }} {{ hostname_name.split('.')[0] }}"
        create: yes

    - name: Sub-task 1 - Install DNS server with Docker
      include_tasks: dns-server.yml
