# -------------------------------------------------
# Ask group action
# -------------------------------------------------
- name: Ask Preparing Action
  pause:
    prompt: |
      ===================================
      Select Type of Node:

      1. Install Harbor & Run Harbor
      2. Install Prerequisites
      3. Download Harbor Project
      4. Generate Harbor configurations
      5. Run Harbor
      6. Exit

      Choose action (1-4):
  register: type_node

- name: Set action fact
  set_fact:
    group_action: "{{ type_node.user_input | trim }}"

# -----------------------------
# Starting Preparing Based On Node
# -----------------------------
- name: Preparing Setup Harbor
  ansible.builtin.include_tasks: main.yml
  when: type_node.user_input | trim == '1'

- name: Install Prerequisites
  ansible.builtin.include_tasks: prerequisites.yml
  when: type_node.user_input | trim == '2'

- name: Download Harbor Project
  ansible.builtin.include_tasks: download.yml
  when: type_node.user_input | trim == '3'

- name: Generate Harbor configurations
  ansible.builtin.include_tasks: configure.yml
  when: type_node.user_input | trim == '4'

- name: Run Harbor With Docker
  ansible.builtin.include_tasks: start.yml
  when: type_node.user_input | trim == '5'
  
- name: Exit
  debug:
    msg: "Goodbye!"
  when: type_node.user_input | trim == '6'

- meta: end_play
  when: type_node.user_input | trim == ''

  vars:
    operation_map:
      '1': 'bastion'
      '2': 'master'
      '3': 'worker'
      '4': 'exit'
